const SYSTEMS = [
    { id: "openhash-system", port: 5037, icon: "⛓️", category: "tech",
      name: { ko: "오픈해시 기술", en: "OpenHash Technology", zh: "OpenHash技术", ja: "OpenHash技術" },
      desc: { ko: "블록체인 대체 차세대 분산 신뢰 기술", en: "Next-gen Distributed Trust Technology", zh: "下一代分布式信任技术", ja: "次世代分散型信頼技術" }},
    { id: "private-data-vault", port: 5025, icon: "🔐", category: "tech",
      name: { ko: "프라이빗 데이터 금고", en: "Private Data Vault", zh: "私人数据保险库", ja: "プライベートデータ金庫" },
      desc: { ko: "오픈해시 기반 개인정보 주권 보장 시스템", en: "OpenHash-based Personal Data Sovereignty", zh: "OpenHash个人数据主权系统", ja: "OpenHash個人情報主権システム" }},
    { id: "national-data-registry", port: 5026, icon: "🔍", category: "tech",
      name: { ko: "국가데이터처", en: "National Data Registry", zh: "国家数据局", ja: "国家データ庁" },
      desc: { ko: "정부 데이터의 구글 - 5계층 424만 TPS", en: "Government Data Search Engine - 5 Layers 4.24M TPS", zh: "政府数据搜索引擎", ja: "政府データ検索エンジン" }},
    { id: "currency", port: 5001, icon: "💱", category: "finance",
      name: { ko: "디지털 화폐 시스템", en: "Digital Currency System", zh: "数字货币系统", ja: "デジタル通貨システム" },
      desc: { ko: "오픈해시 기반 국가 디지털 화폐 플랫폼", en: "OpenHash-based National Digital Currency Platform", zh: "基于OpenHash的国家数字货币平台", ja: "OpenHash基盤国家デジタル通貨" }},
    { id: "education", port: 5003, icon: "🎓", category: "education",
      name: { ko: "교육부 업무자동화", en: "Education Automation", zh: "教育自动化", ja: "教育自動化" },
      desc: { ko: "AI 기반 교육부 행정 자동화 시스템", en: "AI-based Ministry of Education Automation", zh: "AI教育部自动化系统", ja: "AI教育省自動化システム" }},
    { id: "food-drug-safety", port: 5006, icon: "🍽️", category: "welfare",
      name: { ko: "식약처 안전관리", en: "Food & Drug Safety", zh: "食药安全", ja: "食品医薬品安全" },
      desc: { ko: "식품의약품 안전 통합 관리", en: "Food and Drug Safety Administration", zh: "食品药品安全管理", ja: "食品医薬品安全管理" }},
    { id: "healthcare", port: 5005, icon: "🏥", category: "welfare",
      name: { ko: "의료 통합 시스템", en: "Healthcare System", zh: "医疗系统", ja: "医療システム" },
      desc: { ko: "오픈해시 기반 국가 의료 통합", en: "OpenHash-based National Healthcare", zh: "OpenHash医疗平台", ja: "OpenHash医療統合" }},
    { id: "jeju-hospital", port: 5007, icon: "🏨", category: "jeju",
      name: { ko: "제주 권역 의료 AI", en: "Jeju Medical AI", zh: "济州医疗AI", ja: "済州医療AI" },
      desc: { ko: "제주 의료 AI 협진 시스템", en: "Jeju Medical AI Collaboration", zh: "济州医疗AI协作", ja: "済州医療AI協診" }},
    { id: "jeju-integrated", port: 5008, icon: "🌴", category: "jeju",
      name: { ko: "제주 통합 플랫폼", en: "Jeju Integrated Platform", zh: "济州综合平台", ja: "済州統合プラットフォーム" },
      desc: { ko: "제주 행정·관광·생활 통합", en: "Jeju Integrated Services", zh: "济州综合服务", ja: "済州統合サービス" }},
    { id: "judicial", port: 5010, icon: "⚖️", category: "legal",
      name: { ko: "예방적 사법 시스템", en: "Preventive Justice", zh: "预防性司法", ja: "予防的司法" },
      desc: { ko: "AI 기반 범죄 예방 및 사법", en: "AI-based Crime Prevention", zh: "AI犯罪预防", ja: "AI犯罪予防" }},
    { id: "k12", port: 5011, icon: "📚", category: "education",
      name: { ko: "초중고 교육 시스템", en: "K-12 Education", zh: "K-12教育", ja: "K-12教育" },
      desc: { ko: "K-12 맞춤형 AI 교육", en: "K-12 Personalized AI Education", zh: "K-12个性化AI教育", ja: "K-12パーソナライズ教育" }},
    { id: "lawsuit", port: 5012, icon: "👨‍⚖️", category: "legal",
      name: { ko: "AI 전자소송 시스템", en: "AI E-Litigation", zh: "AI电子诉讼", ja: "AI電子訴訟" },
      desc: { ko: "AI 변호사 대리 전자소송", en: "AI Lawyer Electronic Litigation", zh: "AI律师电子诉讼", ja: "AI弁護士電子訴訟" }},
    { id: "legislation", port: 5013, icon: "📜", category: "legal",
      name: { ko: "법제처 업무자동화", en: "Legislation Automation", zh: "立法自动化", ja: "立法自動化" },
      desc: { ko: "법령 입안·심사·해석 자동화", en: "Law Drafting and Review", zh: "法律起草审查", ja: "法令起草・審査" }},
    { id: "local-admin", port: 5014, icon: "🏛️", category: "admin",
      name: { ko: "통합 자치행정", en: "Local Government", zh: "地方政府", ja: "地方自治" },
      desc: { ko: "전국 243개 지자체 통합", en: "Integrated Local Government", zh: "243个地方政府", ja: "243地方自治体統合" }},
    { id: "market", port: 5015, icon: "📈", category: "finance",
      name: { ko: "FPGA 시장 플랫폼", en: "FPGA Market Platform", zh: "FPGA市场平台", ja: "FPGA市場プラットフォーム" },
      desc: { ko: "FPGA 가속 자율 시장", en: "FPGA Accelerated Market", zh: "FPGA加速市场", ja: "FPGA加速市場" }},
    { id: "intellectual-property", port: 5016, icon: "💡", category: "legal",
      name: { ko: "지식재산권 시스템", en: "IP Management", zh: "知识产权", ja: "知的財産" },
      desc: { ko: "AI 기반 지식재산권 관리", en: "AI-based IP Management", zh: "AI知识产权管理", ja: "AI知的財産管理" }},
    { id: "meal", port: 5017, icon: "🍱", category: "welfare",
      name: { ko: "국가 급식 시스템", en: "National Meal System", zh: "国家餐饮", ja: "国家給食" },
      desc: { ko: "AI 기반 전국민 맞춤형 급식", en: "AI-based National Meal Service", zh: "AI定制餐饮", ja: "AIカスタマイズ給食" }},
    { id: "patents", port: 5018, icon: "📋", category: "legal",
      name: { ko: "특허 AI 포털", en: "Patent AI Portal", zh: "专利AI门户", ja: "特許AIポータル" },
      desc: { ko: "특허 출원·심사·분석 AI", en: "Patent Application AI", zh: "专利申请AI", ja: "特許出願AI" }},
    { id: "personnel-innovation", port: 5019, icon: "👥", category: "admin",
      name: { ko: "인사혁신 시스템", en: "HR Innovation", zh: "人事创新", ja: "人事革新" },
      desc: { ko: "공무원 인사·채용·평가", en: "Public Employee HR", zh: "公务员人事", ja: "公務員人事" }},
    { id: "tax", port: 5020, icon: "💰", category: "finance",
      name: { ko: "국세 행정 시스템", en: "Tax Administration", zh: "税务行政", ja: "国税行政" },
      desc: { ko: "지능형 세금 신고·납부·환급", en: "Intelligent Tax Filing", zh: "智能税务", ja: "インテリジェント税務" }},
    { id: "traffic", port: 5021, icon: "🚗", category: "infra",
      name: { ko: "지능형 교통 시스템", en: "Smart Traffic", zh: "智能交通", ja: "スマート交通" },
      desc: { ko: "전국 교통 관제·최적화", en: "Intelligent Transportation", zh: "交通管制优化", ja: "交通管制最適化" }},
    { id: "university", port: 5022, icon: "🎓", category: "education",
      name: { ko: "대학교육 시스템", en: "University Education", zh: "大学教育", ja: "大学教育" },
      desc: { ko: "AI 기반 고등교육 혁신", en: "AI-based Higher Education", zh: "AI高等教育", ja: "AI高等教育" }}
];
